---
- name: Install apache2
  apt:
    name: apache2
    state: present

- name: Enable apache modules
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
    - ssl
    - proxy
    - proxy_http
    - headers
  notify: restart apache

- name: Configure apache vhosts
  template:
    src: "{{ item }}"
    dest: "/etc/apache2/sites-available/{{ item | basename }}"
  with_fileglob:
    - "templates/apache/sites-available/*"
  notify: reload apache

- name: Activate apache vhosts
  file:
    src: "/etc/apache2/sites-available/{{ item | basename }}"
    dest: "/etc/apache2/sites-enabled/{{ item | basename }}"
    owner: root
    group: root
    state: link
  with_fileglob:
    - "templates/apache/sites-available/*"
  notify: reload apache

- name: Add additional apache configuration
  template:
    src: "{{ item }}"
    dest: "/etc/apache2/conf-available/{{ item | basename }}"
  with_fileglob:
    - "templates/apache/conf-available/*"
  notify: reload apache

- name: Activate additional apache configuration
  file:
    src: "/etc/apache2/conf-available/{{ item | basename }}"
    dest: "/etc/apache2/conf-enabled/{{ item | basename }}"
    owner: root
    group: root
    state: link
  with_fileglob:
    - "templates/apache/conf-available/*"
  notify: reload apache

- name: Configure apache modules
  template:
    src: "{{ item }}"
    dest: "/etc/apache2/mods-available/{{ item | basename }}"
  with_fileglob:
    - "templates/apache/mods-available/*"
  notify: reload apache
