---
- name: Configure MariaDB
  import_tasks: mariadb.yml

- name: Configure OpenNebula
  import_tasks: one.yml

- name: Add api user
  import_tasks: one-api-user.yml

- name: Configure disks
  import_tasks: disk.yml

- name: Configure passwordless ssh
  import_tasks: ssh.yml

- name: Configure python packages
  import_tasks: pip.yml
