---
- name: Refresh apt cache
  apt:
    update_cache: yes
  changed_when: false

- name: Configure MariaDB
  import_tasks: mariadb.yml

- name: Configure OpenNebula
  import_tasks: one.yml

- name: Configure apache
  import_tasks: apache.yml

- name: Configure disks
  import_tasks: disk.yml

- name: Configure cron jobs
  import_tasks: cron.yml

- name: Configure passwordless ssh
  import_tasks: ssh.yml
  tags: onehost

- name: Configure python pip packages
  import_tasks: pip.yml

- name: Configure OpenNebula hosts
  import_tasks: hosts.yml
  tags: onehost

- name: Provision OpenNebula virtual machines
  import_tasks: vms.yml
  tags: onevm
