---
- name: Configure MariaDB
  ansible.builtin.import_tasks: mariadb.yml

- name: Configure OpenNebula
  ansible.builtin.import_tasks: one.yml

- name: Add api user
  ansible.builtin.import_tasks: one-api-user.yml

- name: Configure OpenNebula datastores
  ansible.builtin.import_tasks: one-datastores.yml

- name: Configure disks
  ansible.builtin.import_tasks: disk.yml

- name: Configure passwordless ssh
  ansible.builtin.import_tasks: ssh.yml

- name: Configure python packages
  ansible.builtin.import_tasks: pip.yml
