---
- name: Add OpenNebula apt signing key
  apt_key:
    id: "{{ one_apt_key_fingerprint }}"
    url: https://downloads.opennebula.org/repo/repo.key
    state: present

- name: Add OpenNebula {{ one_version }} apt repository
  apt_repository:
    repo: deb https://downloads.opennebula.org/repo/{{ one_version }}/{{ ansible_distribution }}/{{ ansible_distribution_version }} stable opennebula
    filename: opennebula
    update_cache: yes
    state: present

- name: Install OpenNebula and Sunstone
  apt:
    name:
      - opennebula
      - opennebula-sunstone
    state: present

- name: Set oneadmin password
  template:
    src: one/one_auth
    dest: /var/lib/one/.one/one_auth
    owner: oneadmin
    group: oneadmin
    mode: '0600'
  no_log: true
  notify:
    - restart opennebula msg
    - restart opennebula-scheduler

- name: Configure /etc/one/oned.conf
  template:
    src: one/oned.conf
    dest: /etc/one/oned.conf
    owner: root
    group: oneadmin
    mode: '0640'
  no_log: true
  notify: restart opennebula msg

- name: Create OpenNebula ssl directory
  file:
    path: /etc/one/ssl
    state: directory
    owner: root
    group: oneadmin
    mode: u=rwx,g=rx,o=

- name: Configure /etc/one/sunstone-server.conf
  template:
    src: one/sunstone-server.conf
    dest: /etc/one/sunstone-server.conf
    owner: root
    group: oneadmin
    mode: '0640'
  notify:
    - restart opennebula-sunstone
    - restart opennebula-novnc

- name: Configure /etc/one/auth/ldap_auth.conf
  template:
    src: one/ldap_auth.conf
    dest: /etc/one/auth/ldap_auth.conf
    owner: root
    group: oneadmin
    mode: '0644'

- name: Start and enable OpenNebula services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - opennebula
    - opennebula-sunstone
