---
- name: Set authorized keys
  ansible.builtin.template:
    src: ssh/authorized_keys
    dest: /var/lib/one/.ssh/authorized_keys
    owner: oneadmin
    group: oneadmin
    mode: u=rw,g=,o=

- name: Configure known hosts
  ansible.builtin.template:
    src: ssh/known_hosts
    dest: /var/lib/one/.ssh/known_hosts
    owner: oneadmin
    group: oneadmin
    mode: u=rw,g=,o=

- name: Add oneadmin private ssh key
  ansible.builtin.copy:
    content: "{{ one_ssh_privkey }}"
    dest: /var/lib/one/.ssh/id_{{ one_ssh_key_type }}
    owner: oneadmin
    group: oneadmin
    mode: u=rw,g=,o=
  no_log: true
