---
- name: Provision virtual machines
  community.general.one_vm:
    api_url: "{{ one_api_url }}"
    api_username: "{{ one_api_username }}"
    api_password: "{{ one_api_token }}"
    exact_count: 1
    count_labels:
      - ansible-managed
    count_attributes:
      NAME: "{{ item.name }}"
    template_id: "{{ item.template_id }}"
    disk_size: "{{ item.disk_size }}"
    memory: "{{ item.memory }}"
    cpu: "{{ item.cpu }}"
    vcpu: "{{ item.vcpu }}"
    networks: "{{ item.networks }}"
    state: present
  with_items: "{{ one_vms }}"
