---
- name: restart opennebula msg
  ansible.builtin.debug:
    msg: >
      OpenNebula needs to be restarted for changes to take effect.
      Before restarting,
      please make sure there are no virtual machines in a transient state (prolog, migr, epil, save).
      Wait until these virtual machines are in a final state (runn, suspended, stopped, done).

- name: restart opennebula-scheduler
  ansible.builtin.service:
    name: opennebula-scheduler
    state: restarted

- name: restart opennebula-sunstone
  ansible.builtin.service:
    name: opennebula-sunstone
    state: restarted

- name: restart opennebula-novnc
  ansible.builtin.service:
    name: opennebula-novnc
    state: restarted

- name: restart opennebula-hem
  ansible.builtin.service:
    name: opennebula-hem
    state: restarted

- name: onehost sync
  ansible.builtin.command:
    cmd: onehost sync --force
  become: yes
  become_user: oneadmin
