---
role_name_check: 1
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ${MOLECULE_DOCKER_IMAGE:-ubuntu:latest}
    pre_build_image: false
    override_command: false
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  log: true
  inventory:
    hosts:
      all:
        children:
          opennebula_host_servers:
            hosts:
              instance:
verifier:
  name: ansible
